config/routes.rb
Rails.application.routes.draw do
  get 'side/questions'
  get 'side/news'
  get 'side/contact'
  get 'search/index'
  get 'access/new'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  post 'access/new', to: 'access#create'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  get 'shopper/index'
  resources :products
  root "shopper#index", as: 'root'
  get '/shopper', to: 'shopper#index'
  get '/admin', to: 'admin#index'
  get '/login', to: 'access#new'
  post '/login', to: 'access#create'
  get '/logout', to: 'access#destroy'
  post '/logout', to: 'access#destroy'
  get '/search', to: 'search#index'
  post '/search', to: 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :lineitems, dependent: :destroy

	def add_item(product_id)
		current_item = lineitems.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
		else 
			current_item = lineitems.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		lineitems.to_a.sum {|item| item.item_total_price}
	end
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true
  
  def item_total_price
  	quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :lineitems, dependent: :destroy
	PAYMENT_TYPES = ["Check", "Cash", "Credit Card"]
	validates :name, :address, :email, presence: true
	validates :paytype, inclusion: PAYMENT_TYPES
	def add_items_from_cart(cart)
		cart.lineitems.each do |item|
			item.cart_id = nil
			item.order_id = self.id
		end
	end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :lineitems
	before_destroy :make_sure_no_line_items
	validates :name, :description, :image, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01} 
	validates :name, uniqueness: true 
	validates :image, allow_blank: true,
	format: {with: %r{\.(gif|jpg|png)\Z}i, message: 'must be GIF, JPG, PNG images'}

	def make_sure_no_line_items
		if lineitems.empty?
			return true
		else 
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to shopper_index_url, notice: 'Your shopping cart is currently empty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/side_controller.rb
class SideController < ApplicationController
	 skip_before_action :authorize
  def questions
  end

  def news
  end

  def contact
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shopper_helper.rb
module ShopperHelper
end

app/helpers/side_helper.rb
module SideHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <a class="navbar-brand" href="/shopper">Home</a>
     <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="/side/questions">Questions</a></li>
        <li class="nav-item"><a class="nav-link" href="/side/news">News</a></li>
         <li class="nav-item"><a class="nav-link" href="/side/contact">Contact</a></li>
      <% if session[:user_id] %>
        <li class="nav-item"><%= link_to 'Orders', orders_path ,{class: 'nav-link'} %></li>
        <li class="nav-item"><%= link_to 'Products', products_path, {class: 'nav-link'} %></li>
        <li class="nav-item"><%= link_to 'Users', users_path, {class: 'nav-link'} %></li>
      <% end %>
      </ul>
      <%= form_tag("/search",  {class: 'form-inline my-2 my-lg-0'}) do %>
          <%= text_field_tag(:query, value = nil, {class: 'form-control mr-sm-2'})%>
          <%= submit_tag("Search", {class: 'btn btn-outline-success my-2 my-sm-0'}) %>
      <% end %>
      <% if session[:user_id] %>
        <%= button_to 'Logout', logout_path, {class: "btn btn-dark"}%>
      <% else %>
        <%= button_to 'Login', login_path, {class: "btn btn-dark"}%>
      <% end %>
    </nav>
    <div id="columns">
      <div id="side">
        <div id="cart">
          <% if @cart %>
          <%= render @cart %>
          <%end%>
        </div>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </div>
</body>
</html>